[package]
name = "synstructure"
version = "0.2.0"
authors = ["Michael Layzell <michael@thelayzells.com>"]

description = "expand_substructure-like helpers for syn macros 1.1 derive macros"
documentation = "https://docs.rs/synstructure"
repository = "https://github.com/mystor/synstructure"
readme = "README.md"
license = "MIT"
keywords = ["syn", "macros", "derive", "expand_substructure", "enum"]


[dependencies]
syn = "0.9"
quote = "0.3"
